apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gby273t8k-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/gby273t8k-java-quarkus-gitops